image:
  repository: jordisalazarbadia/chat-tasks
  tag: "529478f99d7c61ac8e4efe4aa51a19c430271bd7"
  pullPolicy: Always
  containerPort: 8080

secret:
  name: chat-tasks-sealedsecret
  namespace: prod

replicaCount: 1

securityContext: {}
